# Site settings
title: Gaberber
email: guanzh.wang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog site for random thoughts and mumbling.
baseurl: "/2011011082/Archive/" # the subpath of your site, e.g. /blog/
url: "http://learn.tsinghua.edu.cn:8080" # the base hostname & protocol for your site
twitter_username: cnhajzwgz
github_username:  gaberber

# Build settings
markdown: kramdown
