# Site settings
title: 'Gaberber' # Your Title
tagline: 'My random thoughts and notes' # A brief tagline for your site
sidebar_image: /images/cover.jpg
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gaberber.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: rouge
